import {useState} from 'react';
import {ArrowRight,BookOpen,Search,ShieldCheck} from 'lucide-react';

const glossary=[
 ['Digital twin','A simplified, interactive model of a real place. Here it is a warehouse you can experiment with safely.'],
 ['AMR / robot','Autonomous Mobile Robot. Each colored vehicle picks one order at a time and takes it to a dispatch bay. Click a robot or its fleet button to inspect it.'],
 ['Order wave','A batch of orders to process together. The demo starts with 48. Importing a CSV replaces the current batch and restarts the simulation clock.'],
 ['Shelf / zone','A shelf is a pick location, such as A1. The letter is the storage zone (A–D), and the number is its location (1–4). Raised blocks on the floor are storage racks.'],
 ['Dispatch bay','The place where an order is delivered. The warehouse has three bays: D01, D02 and D03. A delivered order counts as complete.'],
 ['Tick / simulated time','One tick represents 10 seconds inside the model. At 1× playback, the app advances one tick every half-second; 4× advances four. It is accelerated simulation time, not a real clock.'],
 ['Throughput','How many orders have been completed per simulated hour since the wave started. It starts at zero and changes as deliveries happen. Higher usually means faster output.'],
 ['On-time delivery','The percentage of completed orders delivered by their deadline. Queued and in-progress orders are excluded. A dash means no order has been delivered yet.'],
 ['Overdue / at risk','An unfinished order whose deadline has already passed. This is a count of currently overdue orders, not a prediction of future lateness.'],
 ['Fleet utilization','The percentage of the six robots currently assigned to work. Loading and delivering count as active; standby does not.'],
 ['FIFO','First in, first out. Robots take orders in their original file order. This is the starting policy.'],
 ['Nearest pick','Robots prefer a nearby shelf, using grid distance to choose an order. Their actual route finds a shortest walkable path around racks and closures.'],
 ['Urgent first','Robots select urgent orders before standard ones, then earlier deadlines. This policy does not guarantee better performance; compare the measured results.'],
 ['Plan / projection','A saved comparison of three policies over the next 30 simulated minutes, all starting from the same snapshot. A projection is a model result, not a real-world promise.'],
 ['Approval / rejection','Approve applies the recommended policy to future assignments. Reject leaves the current policy unchanged. Robots already carrying out an order keep that assignment.'],
 ['Stale plan','A plan based on an older wave, aisle configuration or policy. It cannot be applied. Generate a fresh comparison. Time passing alone does not invalidate a plan.'],
 ['Deterministic mode','The same input produces the same simulation results. No language model or API key is needed. LangChain tools and the LangGraph workflow still run.'],
 ['MCP','Model Context Protocol: a standard way for an AI assistant to call an application’s tools. Waypoint exposes inspection, simulation and reviewed planning to compatible clients.'],
];
const stack=[
 ['Game engine · Phaser','Draws the warehouse, animates robots, and handles selection, route overlays and zoom. The Python backend owns the actual simulation state.'],
 ['FastAPI','The Python backend. It accepts commands from the website or MCP server, validates order files, advances the simulation and saves results.'],
 ['LangChain','Connects the planner to tools and, optionally, a language model. In this app its tools inspect the warehouse and compare policies.'],
 ['LangGraph','Runs the steps in order: inspect → simulate → recommend → wait for your approval. It saves the workflow so a pending plan can survive a backend restart when storage is retained.'],
 ['MCP server','A separate stdio process launched by your AI client. It calls the same FastAPI backend, so the assistant and website operate on the same warehouse.'],
];

export default function Guide({onFloor,onConnections}:{onFloor:()=>void;onConnections:()=>void}){
 const [search,setSearch]=useState('');const terms=glossary.filter(([name,meaning])=>`${name} ${meaning}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="guide-page">
  <section className="guide-welcome"><span className="eyebrow">YOUR FIVE-MINUTE FIELD GUIDE</span><h2>From your first order<br/>to your next better decision.</h2><p>You do not need to know the technology to use Waypoint. Start with the demo wave, try a disruption, and compare what happens next.</p><button className="button primary" onClick={onFloor}>Open the warehouse <ArrowRight size={15}/></button></section>
  <section className="guide-section"><div className="guide-section-heading"><span>01</span><div><h2>Take it for a spin</h2><p>The shortest path through the whole project.</p></div></div><div className="guide-steps">
   {[['Start the floor','Open Digital twin and click Run simulation. Use 1×, 2× or 4× to change playback speed. Click Pause to stop advancing time.'],['Inspect an order','Choose a robot from the fleet buttons. Its current order and position appear below. Open Order waves to search orders and filter their status.'],['Try a disruption','In Scenario lab, choose Simulate an aisle closure. The amber cells mark the closed area and active routes update. Choose Reopen aisle to undo it.'],['Ask for a comparison','Choose an objective in Decision copilot, then Find a better flow. The app pauses playback and tests all three policies against your current wave.'],['Make the decision','Read the comparison. Delivered means new completions during the next 30 simulated minutes. Approve plan changes future assignments; Reject keeps the current policy. Resume playback to continue.'],['Keep the evidence','Open Decision log to revisit plans. Export report downloads a JSON file containing the current state, metrics, comparisons and review history.']].map(([title,body],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p></article>)}
  </div></section>
  <section className="guide-section"><div className="guide-section-heading"><span>02</span><div><h2>Bring your own order file</h2><p>One row per order. No spreadsheet formulas or extra columns.</p></div></div><div className="guide-import"><div><p>Click <b>Import orders</b>, then choose a UTF-8 CSV. Up to 250 orders and 256 KB are accepted. A successful import replaces the current wave, resets the clock, and makes old plans inapplicable. Invalid files leave the existing warehouse intact.</p><a className="button secondary" href="/api/sample.csv" download>Download an example CSV <ArrowRight size={14}/></a></div><div><pre>order_id,shelf,priority,due_minutes,units{'\n'}ORDER-001,A1,urgent,15,2{'\n'}ORDER-002,D4,standard,30,3</pre><dl><dt>order_id</dt><dd>A unique ID, 1–40 letters/numbers/dashes/underscores.</dd><dt>shelf</dt><dd>A1–A4, B1–B4, C1–C4 or D1–D4.</dd><dt>priority</dt><dd>Either standard or urgent.</dd><dt>due_minutes</dt><dd>Deadline from wave start; an integer from 1 to 1440.</dd><dt>units</dt><dd>How many items to handle; an integer from 1 to 20.</dd></dl></div></div></section>
  <section className="guide-section"><div className="guide-section-heading"><span>03</span><div><h2>What everything means</h2><p>A plain-language glossary for the controls, metrics and workflow.</p></div></div><label className="guide-search"><Search size={17}/><input aria-label="Search the field guide" placeholder="Look up a term, like throughput or MCP…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="glossary">{terms.map(([name,meaning])=><article key={name}><h3>{name}</h3><p>{meaning}</p></article>)}</div>{!terms.length&&<p className="no-guide-results">No matching term. Try “robot,” “policy,” or “approval.”</p>}</section>
  <section className="guide-section"><div className="guide-section-heading"><span>04</span><div><h2>Five components, explained simply</h2><p>Each one has a specific job.</p></div></div><div className="guide-stack">{stack.map(([name,meaning])=><article key={name}><BookOpen size={18}/><div><h3>{name}</h3><p>{meaning}</p></div></article>)}</div></section>
  <section className="guide-section"><div className="guide-section-heading"><span>05</span><div><h2>Use it from an AI assistant</h2><p>The same operation, through an MCP-compatible client.</p></div></div><ol className="guide-mcp"><li>Run <code>scripts/mcp_config.py</code> from the downloaded project to generate a client configuration.</li><li>Add the generated Waypoint server entry in your MCP client. For the hosted website, set <code>WAYPOINT_API_URL</code> to this site’s HTTPS address and <code>WAYPOINT_ACCESS_TOKEN</code> to your workspace access code. Keep the code out of shared files.</li><li>Ask: <b>“Inspect the warehouse, compare policies, and show me a plan before changing anything.”</b></li><li>Review the plan ID and evidence. Approve explicitly only when you want to change future assignments.</li></ol><button className="button secondary" onClick={onConnections}>View connection details <ArrowRight size={14}/></button></section>
  <section className="guide-limits"><ShieldCheck size={24}/><div><h2>Know what the model can tell you</h2><p>Robots move one cell per tick and load for units + 2 ticks. Paths avoid racks and aisle closures. The model does not include collisions between robots, batteries, acceleration or human traffic. Use it to explore the workflow and compare assumptions, not to control real equipment.</p><p>On Render’s free demo host, the service can sleep and its data can reset after a restart or redeploy. Export any report you want to keep. Locally, SQLite files retain your state until you reset or replace it. Everyone with the same access code shares one warehouse.</p></div></section>
  <section className="guide-section"><div className="guide-section-heading"><span>06</span><div><h2>If something looks wrong</h2></div></div><div className="glossary"><article><h3>The hosted app is waking up</h3><p>A free Render service sleeps when idle. Allow time for it to start, then retry. Avoid repeatedly reloading while it is starting.</p></article><article><h3>I cannot approve this plan</h3><p>A wave, closure or policy changed since the comparison. Run a fresh comparison. A reviewed plan cannot be reviewed twice.</p></article><article><h3>No orders are moving</h3><p>Press Run simulation. If every order is complete, import another wave or use Reset demo. Pausing and closing the browser stop UI-driven advancement.</p></article><article><h3>The model explanation is unavailable</h3><p>Waypoint keeps working in deterministic mode. A configured language model adds prose; it is not required for simulations, recommendations or approvals.</p></article></div></section>
 </div>;
}
