import React, {useCallback,useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,LogOut,LockKeyhole,Activity,ArrowDownToLine,ArrowRight,ArrowUpRight,Box,Check,CheckCheck,ChevronDown,ChevronRight,CircleHelp,Clock3,Code2,Command,FileUp,FlaskConical,GitBranch,Layers3,Loader2,Map,Minus,MoreHorizontal,Pause,Play,Plug,Plus,Radio,RotateCcw,Search,ShieldCheck,SlidersHorizontal,Sparkles,Truck,Workflow,X,Zap} from 'lucide-react';
import Warehouse from './Warehouse';
import Guide from './Guide';
import {api,ApiError,policyNames,simTime,type World,type Plan} from './types';
import './styles.css';

type Tab='floor'|'orders'|'plans'|'connect'|'guide';
const objectives=[{value:'throughput',name:'Maximize throughput'},{value:'on_time',name:'Protect on-time delivery'},{value:'distance',name:'Reduce travel distance'}];

function App(){
 const [world,setWorld]=useState<World|null>(null),[plans,setPlans]=useState<Plan[]>([]),[tab,setTab]=useState<Tab>('floor');
 const [running,setRunning]=useState(false),[speed,setSpeed]=useState(1),[selected,setSelected]=useState('AMR-01'),[routes,setRoutes]=useState(true),[zoom,setZoom]=useState(1);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[toast,setToast]=useState(''),[objective,setObjective]=useState('throughput'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[modal,setModal]=useState<'import'|'reset'|'help'|null>(null),[selectedPlan,setSelectedPlan]=useState<Plan|null>(null);
 const [locked,setLocked]=useState(false),[accessCode,setAccessCode]=useState(''),[hostInfo,setHostInfo]=useState({auth_required:false,ephemeral_storage:false});
 const file=useRef<HTMLInputElement>(null),inflight=useRef(false);
 const notify=(message:string)=>{setToast(message);};
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);}},[toast]);
 const load=useCallback(async()=>{try{const info=await api<{auth_required:boolean;ephemeral_storage:boolean}>('/health');setHostInfo(info);const [w,p]=await Promise.all([api<World>('/workspace'),api<Plan[]>('/plans')]);setWorld(w);setPlans(p);setLocked(false);setError('');}catch(e){if(e instanceof ApiError&&e.status===401){setLocked(true);setRunning(false);}else setError((e as Error).message);}},[]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!running||busy)return;let stopped=false;const timer=setInterval(async()=>{if(inflight.current)return;inflight.current=true;try{const w=await api<World>('/advance',{ticks:speed});if(!stopped){setWorld(w);if(w.metrics.completed===w.metrics.total){setRunning(false);notify('Wave complete. Every order has reached dispatch.');}}}catch(e){setError((e as Error).message);setRunning(false);}finally{inflight.current=false;}},500);return()=>{stopped=true;clearInterval(timer);};},[running,speed,busy]);
 // Refresh external MCP actions while paused without advancing simulated time.
 useEffect(()=>{if(running||busy||locked)return;const timer=setInterval(()=>void load(),4000);return()=>clearInterval(timer);},[running,busy,locked,load]);
 async function action(name:string,fn:()=>Promise<void>){if(busy)return;setBusy(name);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function generate(){setRunning(false);await action('plan',async()=>{const plan=await api<Plan>('/plans',{objective});setPlans(p=>[plan,...p]);setSelectedPlan(plan);notify('Comparison ready. Review the plan before applying.');});}
 async function decide(plan:Plan,approved:boolean){await action('review',async()=>{const result=await api<{run:Plan;workspace:World}>(`/plans/${plan.id}/decision`,{approved});setWorld(result.workspace);setPlans(p=>p.map(r=>r.id===plan.id?result.run:r));setSelectedPlan(result.run);notify(approved?'Policy applied to new robot assignments.':'Plan rejected. Current policy retained.');});}
 async function upload(uploadFile:File){await action('import',async()=>{const form=new FormData();form.append('file',uploadFile);const res=await fetch('/api/import',{method:'POST',body:form});const data=await res.json();if(!res.ok)throw new Error(data.detail||'Import failed');setWorld(data);setSelectedPlan(null);setRunning(false);setModal(null);notify(`${data.orders.length} orders imported. Your new wave is ready.`);});}
 const activePlan=selectedPlan?plans.find(p=>p.id===selectedPlan.id)||selectedPlan:plans.find(p=>p.status==='pending'&&p.workspace_id===world?.id&&p.revision===world?.revision);
 const pending=plans.filter(p=>p.status==='pending'&&p.workspace_id===world?.id&&p.revision===world?.revision).length;
 const robot=world?.robots.find(r=>r.id===selected);
 const filtered=world?.orders.filter(o=>(filter==='all'||o.status===filter)&&(o.id.toLowerCase().includes(query.toLowerCase())||o.shelf.toLowerCase().includes(query.toLowerCase())))||[];
 if(locked)return <div className="login-page"><form onSubmit={e=>{e.preventDefault();void action('login',async()=>{await api('/auth',{access_code:accessCode});setAccessCode('');setLocked(false);await load();});}}><span className="brand-mark">w<span>·</span></span><div className="eyebrow">WAYPOINT · OPERATIONS STUDIO</div><h1>Your warehouse awaits.</h1><p>Enter your workspace access code to open the simulator. Everyone with this code shares the same warehouse.</p><label htmlFor="access-code">Workspace access code</label><div className="login-input"><LockKeyhole size={17}/><input id="access-code" type="password" autoComplete="current-password" value={accessCode} onChange={e=>setAccessCode(e.target.value)} required autoFocus/></div>{error&&<p className="modal-error" role="alert">{error}</p>}<button className="button primary" disabled={!!busy}>{busy?<Loader2 className="spin" size={16}/>:<ArrowRight size={16}/>}Open workspace</button><small>The workspace owner can find the code in Render’s environment settings under WAYPOINT_ACCESS_TOKEN.</small></form></div>;

 return <div className="app-shell">
  <aside className="sidebar">
   <a href="#" onClick={e=>{e.preventDefault();setTab('floor');}} className="brand"><span className="brand-mark">w<span>·</span></span>waypoint<span className="brand-dot"/></a>
   <div className="workspace-select"><span className="workspace-icon"><Box size={17}/></span><div>Acme Fulfillment<small>Operations workspace</small></div><ChevronDown size={14}/></div>
   <span className="nav-label">WORKSPACE</span>
   <nav aria-label="Main navigation">
    <button className={tab==='floor'?'nav active':'nav'} onClick={()=>setTab('floor')}><Map size={18}/>Digital twin<span className="nav-live"/></button>
    <button className={tab==='orders'?'nav active':'nav'} onClick={()=>setTab('orders')}><Layers3 size={18}/>Order waves<span className="nav-count">{world?.metrics.total||0}</span></button>
    <button className={tab==='plans'?'nav active':'nav'} onClick={()=>setTab('plans')}><GitBranch size={18}/>Decision log{pending>0&&<span className="nav-count">{pending}</span>}</button>
    <button className={tab==='connect'?'nav active':'nav'} onClick={()=>setTab('connect')}><Plug size={18}/>Connections</button>
    <button className={tab==='guide'?'nav active':'nav'} onClick={()=>setTab('guide')}><BookOpen size={18}/>Field guide</button>
   </nav>
   <div className="sidebar-note"><span className="tiny-icon"><FlaskConical size={17}/></span><strong>A little foresight.<br/>A better operation.</strong><p>Test the next move before<br/>it becomes the real one.</p><span className="sandbox-label"><span/> SIMULATION SANDBOX</span></div>
   <div className="sidebar-bottom"><button onClick={()=>setModal('help')}><CircleHelp size={17}/>Quick guide<ArrowUpRight size={14}/></button><div className="user"><span className="avatar">OP</span><div>Operations team<small>Local workspace</small></div><MoreHorizontal size={18}/></div></div>
  </aside>
  <main>
   <header className="topbar"><div><span>Workspace</span><ChevronRight size={13}/><b>{tab==='floor'?'Digital twin':tab==='orders'?'Order waves':tab==='plans'?'Decision log':tab==='guide'?'Field guide':'Connections'}</b></div><div className="top-right"><span className="connection"><i/> {world?'Backend connected':'Connecting'}</span><span className="divider"/><button className="icon-button" title="Quick guide" aria-label="Open quick guide" onClick={()=>setModal('help')}><CircleHelp size={18}/></button>{hostInfo.auth_required&&<button className="icon-button" title="Sign out" aria-label="Sign out" onClick={()=>void action('logout',async()=>{setRunning(false);await api('/logout',{});setWorld(null);setLocked(true);})}><LogOut size={16}/></button>}<span className="avatar small">OP</span></div></header>
   <div className="page">
    <div className="page-heading"><div><div className="eyebrow"><span/> OPERATIONS STUDIO <span className="slash">/</span> FACILITY 01</div><h1>{tab==='floor'?'See the floor. Shape the flow.':tab==='orders'?'Every order, in motion.':tab==='plans'?'Better decisions leave a trail.':tab==='guide'?'A little clarity goes a long way.':'One warehouse. More ways in.'}</h1><p>{tab==='floor'?'A living model of your warehouse. Explore what happens next.':tab==='orders'?'Bring your order data into the simulation and follow it through dispatch.':tab==='plans'?'Compare the evidence, review a recommendation, and own the next move.':tab==='guide'?'A simple manual for every tool, term, and next step.':'A connected stack, from your warehouse floor to your AI workspace.'}</p></div><div className="heading-actions"><a className="button secondary export-button" href="/api/export" download><ArrowDownToLine size={15}/>Export report</a><button className="button primary" onClick={()=>{setRunning(false);setModal('import');}}><Plus size={16}/>Import orders</button></div></div>
    {error&&<div className="error-banner" role="alert"><span>{error}</span><button onClick={()=>{setError('');if(!world)void load();}}>{world?'Dismiss':'Retry'}</button></div>}
    {!world?<div className="loading"><Loader2 className="spin" size={26}/><h2>Opening the warehouse</h2><p>Connecting to your local operations backend…</p></div>:<>
    {hostInfo.ephemeral_storage&&<div className="hosting-note"><FlaskConical size={14}/><span>Free demo hosting · the service may sleep and reset data after restarts. Export reports to keep your results.</span><button onClick={()=>setTab('guide')}>Learn more</button></div>}
    {tab!=='guide'&&<section className="metrics" aria-label="Warehouse metrics">
     <Metric title="Orders dispatched" value={world.metrics.completed.toString()} unit={`/ ${world.metrics.total}`} icon={<Box size={17}/>} note={`${world.metrics.queued} waiting in the queue`} progress={world.metrics.completed/world.metrics.total}/>
     <Metric title="Throughput" value={world.metrics.throughput.toFixed(0)} unit="orders / hr" icon={<Activity size={17}/>} note="Observed in simulated time" chart={world.history.map(h=>h.throughput)}/>
     <Metric title="On-time delivery" value={world.metrics.on_time===null?'—':world.metrics.on_time.toFixed(0)} unit={world.metrics.on_time===null?'awaiting dispatch':'%'} icon={<Clock3 size={17}/>} note={world.metrics.at_risk?`${world.metrics.at_risk} open orders past due`:'No overdue orders'} warning={world.metrics.at_risk>0}/>
     <Metric title="Fleet utilization" value={Math.round(world.metrics.active_robots/6*100).toString()} unit="%" icon={<Truck size={17}/>} note={`${world.metrics.active_robots} of 6 robots on assignment`} fleet/>
    </section>}
    {tab==='guide'&&<Guide onFloor={()=>setTab('floor')} onConnections={()=>setTab('connect')}/>}
    {tab==='floor'&&<div className="studio-grid">
     <section className="floor-panel">
      <div className="section-head"><div><span className="section-icon"><Layers3 size={17}/></span><h2>Warehouse floor</h2><span className="pill subtle">PHASER ENGINE</span></div><span className={`live-badge ${running?'playing':''}`}><i/>{running?'Running':'Paused'}</span></div>
      <div className="floor-content"><div className="floor-topline"><div><b>NORTH HUB</b><span>25 × 17 grid <i/> 4 storage zones <i/> 3 dispatch bays</span></div><span className="floor-clock"><Clock3 size={13}/>{simTime(world.tick)}</span></div>
       <Warehouse world={world} selected={selected} onSelect={setSelected} routes={routes} zoom={zoom}/>
       <div className="floor-bottomline"><div className="legend"><span><i className="mint"/>AMR fleet</span><span><i className="rack"/>Storage</span><span><i className="route"/>Active routes</span>{world.incident&&<span><i className="amber"/>Closure</span>}</div><div className="zoom"><button aria-label="Zoom out" disabled={zoom<=.9} onClick={()=>setZoom(z=>Math.max(.9,z-.1))}><Minus size={14}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" disabled={zoom>=1.3} onClick={()=>setZoom(z=>Math.min(1.3,z+.1))}><Plus size={14}/></button></div></div>
      </div>
      <div className="simulation-controls"><div><button disabled={!!busy||world.metrics.completed===world.metrics.total} className="button play-button" onClick={()=>setRunning(!running)}>{running?<Pause size={15}/>:<Play size={15}/>} {running?'Pause':'Run simulation'}</button><div className="speed-control" aria-label="Playback speed">{[1,2,4].map(s=><button key={s} aria-pressed={speed===s} className={speed===s?'selected':''} onClick={()=>setSpeed(s)}>{s}×</button>)}</div><button className="icon-button reset" title="Reset demo" aria-label="Reset demo" onClick={()=>{setRunning(false);setModal('reset');}}><RotateCcw size={16}/></button></div><label className="toggle-label"><input type="checkbox" checked={routes} onChange={e=>setRoutes(e.target.checked)}/><span className="switch"/>Routes</label></div>
      <div className="fleet-section"><div className="mini-heading"><h3>On the floor <span>06</span></h3><span>Select a robot to inspect</span></div><div className="fleet-list">{world.robots.map((r,i)=><button key={r.id} className={`robot-card ${selected===r.id?'selected':''}`} onClick={()=>setSelected(r.id)} aria-pressed={selected===r.id}><span className={`robot-dot robot-${i}`}/><b>{r.id}</b><small>{r.phase==='idle'?'Standby':r.phase}</small></button>)}</div><div className="robot-detail"><Radio size={13}/><b>{robot?.id}</b><span>{robot?.order||'Ready for assignment'}</span><span className="detail-distance">{robot?.distance} cells traveled <span>·</span> ({robot?.pos.join(', ')})</span></div></div>
     </section>
     <aside className="planner-panel"><div className="planner-title"><span className="spark-icon"><Sparkles size={18}/></span><div><h2>Decision copilot</h2><span>Small changes. Measurable impact.</span></div><span className="status-dot"/></div>
      <div className="planner-body"><div className="planner-intro"><span className="eyebrow">YOUR NEXT BEST MOVE</span><h3>What could flow<br/>a little better?</h3><p>Test three dispatch strategies against your current wave, then choose what to put in motion.</p></div>
       <label className="input-label" htmlFor="objective">Optimize for</label><div className="select-wrap"><SlidersHorizontal size={15}/><select id="objective" value={objective} onChange={e=>setObjective(e.target.value)}>{objectives.map(o=><option key={o.value} value={o.value}>{o.name}</option>)}</select><ChevronDown size={14}/></div>
       <button className="button plan-button" disabled={!!busy||world.metrics.queued===0} onClick={()=>void generate()}>{busy==='plan'?<Loader2 size={17} className="spin"/>:<Sparkles size={17}/>} {busy==='plan'?'Testing the possibilities…':'Find a better flow'}{busy!=='plan'&&<ArrowRight size={16}/>}</button>
       <div className="workflow-mini"><span><Check size={11}/>Inspect</span><i/><span><Check size={11}/>Simulate</span><i/><span><ShieldCheck size={12}/>You approve</span></div>
       {activePlan?<PlanCard plan={activePlan} world={world} busy={!!busy} onDecision={approved=>void decide(activePlan,approved)} compact/>:<div className="empty-plan"><Workflow size={25}/><b>A plan starts with a question.</b><p>Your comparison will appear here, with the evidence behind every recommendation.</p></div>}
       <div className="planner-mode"><span/><b>{activePlan?.mode==='model'?'Model explanation enabled':'Deterministic planner'}</b><span className="mode-copy">{activePlan?.mode==='fallback'?'Model unavailable · fallback':'Reproducible simulations'}</span></div>
      </div>
     </aside>
     <section className="event-panel"><div className="section-head"><div><Activity size={16}/><h2>Activity stream</h2></div><span className="muted">SIMULATED TIME</span></div><div className="event-list">{world.events.slice(0,4).map((e,i)=><div key={`${e.tick}-${i}`} className="event-row"><span className={`event-dot ${e.kind}`}/><span>{e.text}</span><time>{simTime(e.tick)}</time></div>)}</div></section>
     <section className={`scenario-panel ${world.incident?'incident-active':''}`}><div className="scenario-head"><span><FlaskConical size={17}/>WHAT IF?</span><span className="pill">SCENARIO LAB</span></div><h3>{world.incident?'The central aisle is closed.':'When the usual route isn’t an option.'}</h3><p>{world.incident?'Robots are routing around the closure. Compare policies to see how the wave responds.':'Close the central aisle and see how your operation adapts in real time.'}</p><button disabled={!!busy} onClick={()=>void action('incident',async()=>{setWorld(await api<World>('/incident',{enabled:!world.incident}));setSelectedPlan(null);notify(world.incident?'Central aisle reopened.':'Aisle closed. All active routes recalculated.');})}>{world.incident?'Reopen aisle':'Simulate an aisle closure'}<ArrowUpRight size={15}/></button></section>
    </div>}
    {tab==='orders'&&<section className="data-panel"><div className="data-toolbar"><div><h2>Current order wave <span className="pill subtle">{world.metrics.total} ORDERS</span></h2><p>Deadlines are relative to the start of this wave.</p></div><a href="/api/sample.csv" download className="button secondary"><ArrowDownToLine size={14}/>Sample CSV</a></div><div className="table-controls"><div className="search"><Search size={16}/><input aria-label="Search orders" placeholder="Search order or shelf…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filter order status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="queued">Queued</option><option value="picking">In progress</option><option value="complete">Complete</option></select><span>{filtered.length} results</span></div><div className="table-scroll"><table><thead><tr><th>Order</th><th>Pick location</th><th>Priority</th><th>Units</th><th>Due at</th><th>Robot</th><th>Status</th></tr></thead><tbody>{filtered.map(o=><tr key={o.id}><td><b>{o.id}</b></td><td><span className="shelf-chip">{o.shelf}</span></td><td><span className={o.priority==='urgent'?'urgent':'muted'}>{o.priority==='urgent'?'↗ Urgent':'Standard'}</span></td><td>{o.units}</td><td className={o.due_tick<world.tick&&o.status!=='complete'?'urgent':''}>{simTime(o.due_tick)}</td><td>{o.robot||'—'}</td><td><span className={`status-chip ${o.status}`}>{o.status==='picking'?'In progress':o.status}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="table-empty">No orders match this search.</div>}</div></section>}
    {tab==='plans'&&<div className="plans-layout"><section className="data-panel"><div className="data-toolbar"><div><h2>Decision history</h2><p>Saved comparisons and operator reviews, across all waves.</p></div><button className="button primary" disabled={!!busy} onClick={()=>void generate()}><Plus size={15}/>New comparison</button></div>{plans.length?plans.map(p=><button className={`plan-history-row ${activePlan?.id===p.id?'selected':''}`} key={p.id} onClick={()=>setSelectedPlan(p)}><span className="history-icon"><GitBranch size={18}/></span><div><b>{policyNames[p.recommendation]}</b><small>{new Date(p.created_at).toLocaleString()} · {p.objective.replace('_',' ')}</small></div><span className={`status-chip ${p.status}`}>{p.status}</span><ChevronRight size={16}/></button>):<div className="empty-plan"><GitBranch size={30}/><h3>Your decisions belong here.</h3><p>Run a comparison to create your first reviewable plan.</p></div>}</section>{activePlan?<section className="data-panel plan-detail"><PlanCard plan={activePlan} world={world} busy={!!busy} onDecision={a=>void decide(activePlan,a)}/></section>:<div className="select-plan"><Workflow size={35}/><p>Select a plan to see its evidence.</p></div>}</div>}
    {tab==='connect'&&<Connections/>}
    <footer><span><span className="footer-mark">w.</span> BUILT FOR THE NEXT MOVE.</span><span>Simulation sandbox <i/> {policyNames[world.policy]} <i/> 10 sec / tick</span><button onClick={()=>setTab('guide')}>Read the field guide<ArrowUpRight size={12}/></button></footer>
    </>}
   </div>
  </main>
  {toast&&<div className="toast" role="status"><CheckCheck size={17}/>{toast}<button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={14}/></button></div>}
  {modal&&<Modal title={modal==='import'?'A new wave starts here.':modal==='reset'?'Start a fresh demo wave?':'Meet your operations studio.'} onClose={()=>setModal(null)}>
   {modal==='import'?<><p>Upload a CSV with up to 250 orders. This replaces the current simulation wave; previous plans stay in the decision log.</p><button className="upload-area" disabled={!!busy} onClick={()=>file.current?.click()}><FileUp size={30}/><b>{busy==='import'?'Importing your wave…':'Choose an orders CSV'}</b><span>UTF-8 · up to 256 KB</span></button><input type="file" ref={file} accept=".csv,text/csv" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/><div className="schema-box"><span>REQUIRED COLUMNS</span><code>order_id, shelf, priority, due_minutes, units</code><p>Shelves A1–D4 · priority standard or urgent · deadlines 1–1440 minutes · units 1–20</p></div><a className="text-link" href="/api/sample.csv" download><ArrowDownToLine size={14}/>Download a ready-to-use example</a>{error&&<p className="modal-error" role="alert">{error}</p>}</>:modal==='reset'?<><p>The current wave and robot positions will be replaced by the 48-order sample. Your decision history is preserved.</p><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Keep current wave</button><button className="button primary" disabled={!!busy} onClick={()=>void action('reset',async()=>{setWorld(await api<World>('/reset',{}));setSelectedPlan(null);setModal(null);notify('Fresh demo wave loaded.');})}>Reset simulation</button></div></>:<><p>Waypoint turns an order file into a warehouse you can explore, measure, and improve.</p><ol className="guide-list"><li><b>Bring a wave.</b> Use the included 48 orders or import your own CSV.</li><li><b>Watch the floor.</b> Run the simulation, inspect a robot, or close an aisle.</li><li><b>Compare the possibilities.</b> Choose an objective and test three dispatch policies.</li><li><b>Make the call.</b> Approve a plan, then export the evidence.</li></ol><button className="button primary" onClick={()=>{setModal(null);setTab('guide');}}><BookOpen size={15}/>Read the full field guide</button><div className="assumptions"><ShieldCheck size={19}/><p>This is a planning sandbox. Robots move one grid cell per tick; loading takes units + 2 ticks. It models racks and closures, but not robot collisions, battery life or human traffic. Projections are not real-world guarantees.</p></div></>}
  </Modal>}
 </div>;
}

function Metric({title,value,unit,icon,note,progress,chart,warning,fleet}:{title:string;value:string;unit:string;icon:React.ReactNode;note:string;progress?:number;chart?:number[];warning?:boolean;fleet?:boolean}){return <div className="metric"><div className="metric-title">{title}<span>{icon}</span></div><div className="metric-value">{value}<span>{unit}</span></div><div className={`metric-note ${warning?'warning':''}`}>{warning?<span className="warning-dot"/>:<span className="mini-dot"/>}{note}</div>{progress!==undefined&&<div className="progress-track"><div style={{width:`${progress*100}%`}}/></div>}{chart&&<svg className="sparkline" viewBox="0 0 120 28" aria-hidden="true"><path d={chart.length>1?chart.slice(-20).map((v,i,a)=>`${i?'L':'M'}${i/(a.length-1)*120},${26-v/Math.max(...a,1)*23}`).join(' '):'M0,25 L120,25'} fill="none" stroke="#829d67" strokeWidth="1.7"/></svg>}{fleet&&<div className="fleet-bars" aria-hidden="true">{Array.from({length:20},(_,i)=><i key={i} className={i<Number(value)/5?'filled':''}/>)}</div>}</div>;}

function PlanCard({plan,world,busy,onDecision,compact=false}:{plan:Plan;world:World;busy:boolean;onDecision:(a:boolean)=>void;compact?:boolean}){const stale=plan.workspace_id!==world.id||plan.revision!==world.revision;return <div className={`plan-card ${compact?'compact':''}`}><div className="plan-card-top"><span><Sparkles size={13}/> RECOMMENDATION</span><span className={`status-chip ${plan.status}`}>{plan.status==='pending'?'Review needed':plan.status}</span></div><h3>{policyNames[plan.recommendation]}</h3><p>{plan.summary}</p><div className="comparison-table"><div className="comparison-header"><span>30-min projection</span><span>Delivered¹</span><span>On time²</span></div>{plan.comparisons.map(c=><div className={c.policy===plan.recommendation?'best':''} key={c.policy}><span>{policyNames[c.policy]}{c.policy===plan.recommendation&&<Check size={12}/>}</span><b>{c.newly_completed}</b><span>{c.on_time===null?'—':`${c.on_time}%`}</span></div>)}</div><small className="projection-note">¹ New deliveries · ² All completed orders<br/>Snapshot {simTime(plan.based_on_tick)} · projections, not guarantees</small>{!compact&&<div className="trace">{plan.trace.map((t,i)=><div key={t.step}><span>{i+1}</span><div><b>{t.step}</b><small>{t.detail}</small></div></div>)}</div>}{plan.status==='pending'&&(stale?<p className="stale-note">The warehouse configuration changed. Run a new comparison before applying.</p>:<div className="review-actions"><button className="button primary" disabled={busy} onClick={()=>onDecision(true)}><Check size={14}/>Approve plan</button><button className="button secondary" disabled={busy} onClick={()=>onDecision(false)}>Reject</button></div>)}</div>;}

function Connections(){const [copied,setCopied]=useState(false);const hosted=window.location.hostname!=='localhost'&&window.location.hostname!=='127.0.0.1';const config=JSON.stringify({mcpServers:{waypoint:{command:'/ABSOLUTE/PATH/waypoint/.venv/bin/python',args:['/ABSOLUTE/PATH/waypoint/backend/mcp_server.py'],env:{WAYPOINT_API_URL:window.location.origin,...(hosted?{WAYPOINT_ACCESS_TOKEN:'YOUR_WORKSPACE_ACCESS_CODE'}:{})}}}},null,2);return <div className="connections-layout"><section className="connection-hero"><div className="eyebrow">FIVE PARTS. ONE CONNECTED SYSTEM.</div><h2>The floor meets<br/>your AI workspace.</h2><p>Inspect the same warehouse from an MCP client. Every action goes through the API, and every plan leaves an auditable decision.</p><div className="stack-flow">{[{name:'Phaser',detail:'Interactive floor',icon:Map},{name:'FastAPI',detail:'State & endpoints',icon:Zap},{name:'LangChain',detail:'Tools & models',icon:Layers3},{name:'LangGraph',detail:'Durable approvals',icon:GitBranch},{name:'MCP',detail:'Assistant access',icon:Plug}].map(({name,detail,icon:Icon})=><div key={name}><Icon size={22}/><b>{name}</b><span>{detail}</span></div>)}</div></section><section className="data-panel connection-setup"><div className="data-toolbar"><div><h2><Plug size={18}/>Connect an MCP client</h2><p>Stdio transport · launched by your client</p></div><span className="pill subtle">LOCAL</span></div><p>Replace both absolute paths below with your project location. Add this entry to an MCP client’s server configuration, then use the local backend or this hosted URL. Add your workspace access code only in your private client settings.</p><div className="code-header"><span>mcpServers.json</span><button onClick={()=>void navigator.clipboard.writeText(config).then(()=>setCopied(true)).catch(()=>setCopied(false))}>{copied?<Check size={13}/>:<Code2 size={13}/>} {copied?'Copied':'Copy template'}</button></div><pre>{config}</pre><div className="tool-list">{['inspect_warehouse','advance_simulation','set_aisle_closure','propose_plan','review_plan','list_plans'].map(t=><code key={t}>{t}</code>)}</div><div className="assumptions"><ShieldCheck size={18}/><p>Approval is a separate tool call. Ask your assistant to show the plan first. This local prototype trusts its connected operator; it does not provide multi-user authorization.</p></div></section><section className="prompt-card"><Command size={22}/><span>TRY THIS IN YOUR MCP CLIENT</span><h3>“Inspect the warehouse, compare dispatch policies, and show me a plan before changing anything.”</h3><p>The server also exposes warehouse and model-assumption resources, plus an investigation prompt.</p><a href="/docs" target="_blank" rel="noreferrer" className="text-link">Explore the FastAPI documentation <ArrowUpRight size={14}/></a></section></div>;}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);return <dialog ref={ref} className="modal" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-header"><span className="spark-icon"><Box size={19}/></span><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div><h2>{title}</h2>{children}</dialog>;}

createRoot(document.getElementById('root')!).render(<App/>);
